services:
  frontend:
    build:
      context: ./frontend
      deploy:
        resources:
          limits:
            memory: 714M
            cpus: "1"
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      deploy:
        resources:
          limits:
            memory: 714M
            cpus: "1"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHONUNBUFFERED: 1
    env_file:
      - ./backend/.env

networks:
  app-network:
    driver: bridge
